CameraRGBBaseOptions: &CameraRGBBaseOptions
  "image_size_x": "1600"
  "image_size_y": "900"
  "sensor_tick": "0.083333"
  "fstop": "1.8"
  "shutter_speed": "20.0"

RadarBaseOptions: &RadarBaseOptions
  'horizontal_fov': '80'
  'vertical_fov': '30'
  'points_per_second': '1500'
  'range': '250'
  'sensor_tick': '0.076923'

sensors:
  - 
    name: "CAM_FRONT"
    bp_name: 'sensor.camera.rgb'
    location: 
      x: 0.8
      y: 0
      z: 1.5
    rotation:
      yaw: 0
      pitch: 0
      roll: 0
    options: 
        <<: *CameraRGBBaseOptions
        "fov": "70"
  - 
    name: "CAM_FRONT_RIGHT"
    bp_name: 'sensor.camera.rgb'
    location: 
      x: 0.8
      y: 0.5
      z: 1.5
    rotation:
      yaw: 55
      pitch: 0
      roll: 0
    options: 
        <<: *CameraRGBBaseOptions
        "fov": "70"
  - 
    name: "CAM_FRONT_LEFT"
    bp_name: 'sensor.camera.rgb'
    location: 
      x: 0.8
      y: -0.5
      z: 1.5
    rotation:
      yaw: -55
      pitch: 0
      roll: 0
    options: 
        <<: *CameraRGBBaseOptions
        "fov": "70"
  - 
    name: "CAM_BACK_LEFT"
    bp_name: 'sensor.camera.rgb'
    location: 
      x: -0.5
      y: -0.5
      z: 1.5
    rotation:
      yaw: -110
      pitch: 0
      roll: 0
    options: 
        <<: *CameraRGBBaseOptions
        "fov": "70"
  - 
    name: "CAM_BACK"
    bp_name: 'sensor.camera.rgb'
    location: 
      x: -0.5
      y: 0
      z: 1.5
    rotation:
      yaw: 180
      pitch: 0
      roll: 0
    options: 
        <<: *CameraRGBBaseOptions
        "fov": "110"
  - 
    name: "CAM_BACK_RIGHT"
    bp_name: 'sensor.camera.rgb'
    location: 
      x: -0.5
      y: 0
      z: 1.5
    rotation:
      yaw: 110
      pitch: 0
      roll: 0
    options: 
        <<: *CameraRGBBaseOptions
        "fov": "70"
  #-----------radar----------
  - 
    name: "RADAR_FRONT"
    bp_name: 'sensor.other.radar'
    location: 
      x: 2.04
      y: 0
      z: 1
    rotation:
      yaw: 0
      pitch: 0
      roll: 0
    options: 
        <<: *RadarBaseOptions
  - 
    name: "RADAR_FRONT_RIGHT"
    bp_name: 'sensor.other.radar'
    location: 
      x: 1.8
      y: 0.86
      z: 1
    rotation:
      yaw: 90
      pitch: 0
      roll: 0
    options: 
        <<: *RadarBaseOptions

  - 
    name: "RADAR_FRONT_LEFT"
    bp_name: 'sensor.other.radar'
    location: 
      x: 1.8
      y: -0.86
      z: 1
    rotation:
      yaw: -90
      pitch: 0
      roll: 0
    options: 
        <<: *RadarBaseOptions
  - 
    name: "RADAR_BACK_RIGHT"
    bp_name: 'sensor.other.radar'
    location: 
      x: -1.8
      y: 0.86
      z: 1
    rotation:
      yaw: 90
      pitch: 0
      roll: 0
    options: 
        <<: *RadarBaseOptions
  - 
    name: "RADAR_BACK_LEFT"
    bp_name: 'sensor.other.radar'
    location: 
      x: -1.8
      y: -0.86
      z: 1
    rotation:
      yaw: -90
      pitch: 0
      roll: 0
    options: 
        <<: *RadarBaseOptions

  #-----------lidar----------
  - 
    name: 'LIDAR_TOP'
    bp_name: 'sensor.lidar.ray_cast'
    location: 
      x: 0
      y: 0
      z: 1.5
    rotation:
      yaw: 0
      pitch: 0
      roll: 0
    options: 
      'channels': '32'
      'points_per_second': '200000'
      'range': '80'
      'upper_fov': '10'
      'lower_fov': '-30'
      'horizontal_fov': '360'
      'rotation_frequency': '20'
      'sensor_tick': '0.05'
  #-----------gnss----------
  - 
    name: "GNSS"
    bp_name: 'sensor.other.gnss'
    location: 
      x: 0
      y: 0
      z: 1.5
    rotation:
      yaw: 0
      pitch: 0
      roll: 0
    options: ~
  #-----------imu----------
  - 
    name: "IMU"
    bp_name: 'sensor.other.imu'
    location: 
      x: 0
      y: 0
      z: 1.5
    rotation:
      yaw: 0
      pitch: 0
      roll: 0
    options: ~