dataset:
  root: "./dataset"
  version: "v1.14"

client:
  host: 127.0.0.1
  port: 2000
  time_out: 10.0

sensors:
  !include ./configs/sensors.yaml

categories:
  !include ./configs/categories.yaml

attributes:
  !include ./configs/attributes.yaml

visibility:
  !include ./configs/visibility.yaml 

world:  #map
  map_name: "Town03"
  map_category: "semantic_prior"
  settings:
    fixed_delta_seconds: 0.04
scene:
  calibrated_sensors:
    !include ./configs/calibrated_sensors.yaml
  description:
    "viz"
  ego_bp_name: "vehicle.tesla.model3"
ui:
  width: 1600
  height: 900
viz_camera:
  name: "viz"
  bp_name: 'sensor.camera.rgb'
  location: 
    x: -5
    y: 0
    z: 3
  rotation:
    yaw: 0
    pitch: -15
    roll: 0
  options: 
    "image_size_x": "1600"
    "image_size_y": "900"
    "sensor_tick": "0.04"
    "fstop": "1.8"
    "shutter_speed": "20.0"
    "fov": "70"